(ns megastrike.gui.subs
  (:require
   [cljfx.api :as fx]
   [clojure.string :as str]
   [megastrike.board :as board]
   [megastrike.combat-unit :as cu]))

(defn title-string
  [context]
  (let [force (first (fx/sub-val context :turn-order))
        phase (fx/sub-val context :current-phase)
        turn (fx/sub-val context :turn-number)]
    (if (and force phase turn)
      (str "Megastrike | " (str/capitalize (name force)) " | " (str/capitalize (name phase)) " Phase | Turn #" turn)
      "Megastrike")))

(defn units
  "Returns the map containing all units from the context. The map key is generated by running `(:id u)` where u is the unit map."
  [context]
  (fx/sub-val context :units))

(defn active-id
  "Returns the ID of the active unit. For use in lookups."
  [context]
  (fx/sub-val context :active-unit))

(defn active-unit
  "Returns the actual unit which corresponds to the ID returned by `active-id'."
  [context]
  (get (units context) (active-id context)))

(defn deployed-units
  [context]
  (filter cu/deployed? (vals (units context))))

(defn forces
  [context]
  (fx/sub-val context :forces))

(defn round-report
  [context]
  (fx/sub-val context :round-report))

(defn turn-number
  [context]
  (fx/sub-val context :turn-number))

(defn phase
  [context]
  (fx/sub-val context :current-phase))

(defn turn-order
  [context]
  (fx/sub-val context :turn-order))

(defn current-forces
  [context]
  (filter #(= (cu/get-force %) (first (turn-order context))) (vals (units context))))

(defn units-by-force
  [context]
  (group-by cu/get-force (vals (units context))))

(defn layout
  [context]
  (fx/sub-val context :layout))

(defn board
  [context]
  (fx/sub-val context :game-board))

(defn tiles
  [context]
  (board/tiles (board context)))
