name: Build MacOS Release
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-mac-uberjar:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
      - run: lein uberjar
      - run: chmod +x startup.sh
      - uses: ksm2/archive-action@v1
        id: archive
        with: 
          format: "tar.gz"
          name: megastrike_macos
      - uses: actions/upload-artifact@v3
        with:
          name: mmegastrike_macos
          path: megastrike_macos.tar.gz