name: Build Release Artifacts
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  uberjar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
      - run: lein uberjar
      - name: Set as executable
        run: chmod +x ./target/megastrike-0.1.0-SNAPSHOT-standalone.jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: uberjar
          path: ./target/megastrike-0.1.0-SNAPSHOT-standalone.jar

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
      - run: lein uberjar
      - run: mv ./target/megastrike-0.1.0-SNAPSHOT-standalone.jar ./target/megastrike.jar
      - run: jpackage @jpackage/common @jpackage/linux
      - uses: actions/upload-artifact@v4
        with:
          name: megastrike-0.1-1_amd64.deb
          path: megastrike-0.1-1_amd64.deb
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: megastrike-0.1-1_amd64.deb
      #     asset_name: megastrike-0.1-1_amd64.deb
      #     asset_content_type: application/vnd.debian.binary-package

  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
      - run: lein uberjar
      - run: mv ./target/megastrike-0.1.0-SNAPSHOT-standalone.jar ./target/megastrike.jar
      - run: jpackage @jpackage/common @jpackage/mac
      - uses: actions/upload-artifact@v4
        with:
          name: megastrike-0.1-1.dmg
          path: megastrike-0.1-1.dmg
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: megastrike-0.1.0.dmg
      #     asset_name: megastrike-0.1.0.dmg
      #     asset_content_type: application/x-apple-diskimage

  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
      - run: lein uberjar
      - run: jpackage @jpackage/common @jpackage/windows
      - uses: actions/upload-artifact@v4
        with:
          name: megastrike-0.1.0.exe
          path: megastrike-0.1.0.exe
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: megastrike-0.1.0.exe
      #     asset_name: megastrike-0.1.0.exe
      #     asset_content_type: application/vnd.microsoft.portable-executable