name: Build Release Artifacts
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-deb:
    uses: ./.github/workflows/build-deb.yml
  deploy-deb:
    needs: build-linux-uberjar
    runs-on: ubuntu-latest
    steps:
      - name: Download deb file
        uses: actions/download-artifact@v4
        with:
          name: megastrike_linux_jar
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*
          asset_name: megastrike_${{ github.event.release.tag_name }}_amd64

  build-dmg:
    uses: ./.github/workflows/build-dmg.yml
  deploy-dmg:
    needs: build-mac-uberjar
    runs-on: macos-latest
    steps:
      - name: Download dmg
        uses: actions/download-artifact@v4 
        with: 
          name: megastrike_macos_jar
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*
          asset_name: megastrike-${{ github.event.release.tag_name }}_macos

  build-exe:
    uses: ./.github/workflows/build-exe.yml
  deploy-exe:
    needs: build-win-uberjar
    runs-on: windows-latest
    steps:
      - name: Download exe
        uses: actions/download-artifact@v4
        with:
          name: megastrike_win_jar
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*
          asset_name: megastrike-${{ github.event.release.tag_name }}