name: Build Linux Release
on:
  workflow_dispatch:
  workflow_call:


jobs:
  build-linux-uberjar:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
      - name: Build uberjar
        run: clojure -T:build uber
      - run: chmod +x startup.sh
      - uses: ksm2/archive-action@v1
        id: archive
        with: 
          format: "tar.gz"
          name: megastrike_linux
      - uses: actions/upload-artifact@v3
        with:
          name: megastrike_linux
          path: megastrike_linux.tar.gz
