name: Build Release Artifacts
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-linux-uberjar:
    uses: ./.github/workflows/build-deb.yml
  deploy-deb:
    needs: build-linux-uberjar
    runs-on: ubuntu-latest
    steps:
      - name: Download jar file
        uses: actions/download-artifact@v4
        with:
          name: megastrike_linux
      - run: ls -R
      - name: Build release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: { { github.event.release.tag_name } }
          files: megastrike_linux.tar.gz
          name: megastrike_${{ github.event.release.tag_name }}_amd64

  build-mac-uberjar:
    uses: ./.github/workflows/build-dmg.yml
  deploy-dmg:
    needs: build-mac-uberjar
    runs-on: macos-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v4
        with:
          name: megastrike_macos
      - name: Build release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: { { github.event.release.tag_name } }
          files: megastrike_macos.tar.gz
          name: megastrike_${{ github.event.release.tag_name }}_macos

  build-win-uberjar:
    uses: ./.github/workflows/build-exe.yml
  deploy-exe:
    needs: build-win-uberjar
    runs-on: windows-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v4
        with:
          name: megastrike_win
      - name: Build release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: { { github.event.release.tag_name } }
          files: megastrike_win.zip
          name: megastrike_${{ github.event.release.tag_name }}_win
