name: Build Windows Release
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-win-uberjar:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
      - name: Create Uberjar
        shell: cmd
        run: clj -T:build uber
      - uses: ksm2/archive-action@v1
        id: archive
        with: 
          format: "zip"
          name: megastrike_win
      - uses: actions/upload-artifact@v3
        with:
          name: megastrike_win
          path: megastrike_win.zip
