name: Build Release Artifacts
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-linux-uberjar:
    uses: ./.github/workflows/build-deb.yml
  deploy-deb:
    needs: build-linux-uberjar
    runs-on: ubuntu-latest
    steps:
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: megastrike_linux
      - run: ls -R
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: megastrike_linux.tar.gz
          asset_name: megastrike_${{ github.event.release.tag_name }}_amd64
          asset_content_type: application/gzip

  build-mac-uberjar:
    uses: ./.github/workflows/build-dmg.yml
  deploy-dmg:
    needs: build-mac-uberjar
    runs-on: macos-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v3 
        with: 
          name: megastrike_macos
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: megastrike_macos.tar.gz
          asset_name: megastrike-${{ github.event.release.tag_name }}_macos.tar.gz
          asset_content_type: application/gzip

  build-win-uberjar:
    uses: ./.github/workflows/build-exe.yml
  deploy-exe:
    needs: build-win-uberjar
    runs-on: windows-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: megastrike_win
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: megastrike_win.zip
          asset_name: megastrike-${{ github.event.release.tag_name }}_win
          asset_content_type: application/zip
