name: Build Release Artifacts
on:
  release:
    types: [created]
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'temurin'
      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
          cmd-exe-workaround: 'latest'
      - run: clojure -A:uberjar
      - run: jpackage @jpackage/common @jpackage/linux
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: cljfx-ms_2.0-0_amd64.deb
          asset_name: cljfx-ms_2.0-0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
          cmd-exe-workaround: 'latest'
      - run: clojure -A:uberjar
      - run: jpackage @jpackage/common @jpackage/mac
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: cljfx-ms-2.0.dmg
          asset_name: cljfx-ms-2.0.dmg
          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      - run: iwr -useb download.clojure.org/install/win-install-1.10.1.536.ps1 | iex
      - run: clojure -A:uberjar
      - run: jpackage @jpackage/common @jpackage/windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: cljfx-ms-2.0.exe
          asset_name: cljfx-ms-2.0.exe
          asset_content_type: application/vnd.microsoft.portable-executable
