name: Build Linux Release
on:
  workflow_dispatch:
  workflow_call:


jobs:
  build-linux-uberjar:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: '1.11.1.1413'
          lein: '2.10.0'
      - run: lein uberjar
      - run: chmod +x startup.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: megastrike_linux_jar
          path: ./*
  # build-deb:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '14'
  #     - uses: DeLaGuardo/setup-clojure@12.5
  #       with:
  #         cli: '1.11.1.1413'
  #         lein: '2.10.0'
  #     - run: lein uberjar
  #     - run: jpackage @jpackage/common @jpackage/linux
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: megastrike_linux
  #         path: '*.deb'