name: Build Release Artifacts
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-deb:
    uses: ./.github/workflows/build-deb.yml
  deploy-deb:
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      - name: Download deb file
        uses: actions/download-artifact@v4
        with:
          name: megastrike_linux
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: megastrike_linux
          asset_name: megastrike_${{ github.event.release.tag_name }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

  build-dmg:
    uses: ./.github/workflows/build-dmg.yml
  deploy-dmg:
    needs: build-dmg
    runs-on: macos-latest
    steps:
      - name: Download dmg
        uses: actions/download-artifact@v4 
        with: 
          name: megastrike_macos
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: megastrike_macos
          asset_name: megastrike-${{ github.event.release.tag_name }}.dmg
          asset_content_type: application/x-apple-diskimage

  build-exe:
    uses: ./.github/workflows/build-exe.yml
  deploy-exe:
    needs: build-exe
    runs-on: windows-latest
    steps:
      - name: Download exe
        uses: actions/download-artifact@v4
        with:
          name: megastrike-windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: megastrike_windows
          asset_name: megastrike-${{ github.event.release.tag_name }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable