name: Build Release Artifacts
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-deb:
    uses: ./.github/workflows/build-deb.yml
  deploy-deb:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Download deb file
        uses: actions/download-artifact@v4
        with:
          name: megastrike_linux
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*
          asset_name: megastrike_${{ github.event.release.tag_name }}_amd64.deb

  build-dmg:
    uses: ./.github/workflows/build-dmg.yml
  deploy-dmg:
    needs: build-mac
    runs-on: macos-latest
    steps:
      - name: Download dmg
        uses: actions/download-artifact@v4 
        with: 
          name: megastrike_macos
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*
          asset_name: megastrike-${{ github.event.release.tag_name }}.dmg

  build-exe:
    uses: ./.github/workflows/build-exe.yml
  deploy-exe:
    needs: build-win
    runs-on: windows-latest
    steps:
      - name: Download exe
        uses: actions/download-artifact@v4
        with:
          name: megastrike_windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*
          asset_name: megastrike-${{ github.event.release.tag_name }}.exe